package net.sourceforge.omov.core.prefs;

enum PrefKey {
    IS_CONFIGURED,
    
    FOLDER_COVERS, FOLDER_TEMPORARY, FOLDER_DATA,
    // SERVER_PORT,
    USERNAME,
    STARTUP_VERSION_CHECK, STARTUP_FILESYSTEM_CHECK,
    
    RECENT_EXPORT_DESTINATION, RECENT_COVER_SELECTOR_PATH, RECENT_MOVIE_FOLDER_PATH, RECENT_SCAN_PATH, RECENT_BACKUP_IMPORT_PATH,
    
    PROXY_HOST, PROXY_PORT, PROXY_ENABLED,
    
    LANGUAGE_CODE
    ;
}
